# Generated by Django 3.1.1 on 2022-08-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway_setting', '0002_auto_20210512_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacsNodeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(max_length=200)),
                ('port', models.IntegerField(default=6002)),
                ('ae_title', models.CharField(max_length=200)),
            ],
        ),
    ]
