# Generated by Django 3.1.1 on 2022-08-02 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway_setting', '0003_pacsnodestatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PacsNodeStatus',
        ),
    ]
